SELECT
    Date AS date,
    Insertion_Order_ID AS insertion_order_id,
    Insertion_Order AS insertion_order,
    Insertion_Order_Status AS insertion_order_status,
    Advertiser_ID AS advertiser_id,
    Advertiser AS advertiser,
    "" AS ad_server_placement_id,
    Exchange_ID AS exchange_id,
    Creative_ID AS creative_id,
    Creative AS creative,
    Exchange AS exchange,
    Line_Item_ID AS line_item_id,
    Line_Item AS line_item,
    Line_Item_Type AS line_item_type,
    Advertiser_Currency AS currency,
    Revenue__USD_ AS media_cost_revenue,
    Media_Cost__USD_ AS mediacost,
    Impressions AS impressions,
    Clicks AS clicks,
    Complete_Views__Video_ AS complete_views_video,
    First_Quartile_Views__Video_ AS first_quartile_views_video,
    Midpoint_Views__Video_ AS midpoint_views_video,
    Third_Quartile_Views__Video_ AS third_quartile_views_video,
    Impressions AS impressions

FROM {DV360_BASE_TABLE}