SELECT
    Date AS date,
    Campaign_ID AS campaign_id,
    Campaign AS campaign,
    Advertiser_ID AS advertiser_id,
    Advertiser AS advertiser,
    Placement AS placement,
    "" AS ad_server_placement_id,
    Placement_ID AS placement_id,
    Package_Roadblock_ID AS package_roadblock_id,
    Package_Roadblock AS package_roadblock,
    Site_ID__CM360_ AS site_id_dfa,
    Site__CM360_ AS site_dfa,
    AD_ID AS ad_id,
    AD AS ad,
    Creative_ID AS creative_id,
    Creative AS creative,
    Creative_Type AS creative_type,
    Click_through_URL AS click_through_url,
    Activity_Group AS activity_group,
    Activity_ID AS activity_id,
    Activity AS activity,
    "" AS dfa_conversions,
    View_through_Conversions AS view_through_conversions,
    Click_through_Conversions AS click_through_conversions,
    "" AS dfa_revenue,
    View_through_Revenue AS view_through_revenue,
    Click_through_Revenue AS click_through_revenue

FROM {CM360_CONVERSIONS_BASE}